version: '3'
services:
  geek-frontend:
    image: frontend:latest
    restart: always
    ports:
      - 8081:80

  geek-crud-example-backend:
    image: registry.heroku.com/geek-lesson-08-crud-example/web:latest
    ports:
      - 8080
    environment:
      DB_HOST: "db"
    restart: always
    depends_on:
      - db
    command: bash -c "/apps/wait-for-service.sh db 3306 && /apps/entrypoint.sh"

  db:
    #    image: postgres
    #    restart: always
    #    environment:
    #      POSTGRES_PASSWORD: password
    #    ports:
    #    - 5432:5432

    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - 3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
